global.numList = [
    {
        mode:1,
        name:'승학',
        organ:'교무처',
        office:'교무처장실',
        number:'200-6100'
    },
    {
        mode:1,
        name:'승학',
        organ:'교무과',
        office:'교무과장실',
        number:'200-6101'
    },
    {
        mode:1,
        name:'승학',
        organ:'학사관리과',
        office:'학사관리과(학적)',
        number:'200-6126~8'
    },
    {
        mode:1,
        name:'승학',
        organ:'학사관리과',
        office:'학사관리과(수업)',
        number:'200-6122~4'
    },
    {
        mode:1,
        name:'승학',
        organ:'연구지원실',
        office:'연구지원실',
        number:'200-6746~8'
    },
    //부민
    {
        mode:2,
        name:'부민',
        organ:'취업지원실',
        office:'FAX',
        number:'200-8773'
    },
    {
        mode:2,
        name:'부민',
        organ:'입학관리과',
        office:'입학상담 1',
        number:'200-5555'
    },
    {
        mode:2,
        name:'부민',
        organ:'입학관리과',
        office:'입학상담 2',
        number:'200-7777'
    },
    {
        mode:2,
        name:'부민',
        organ:'국제교류처',
        office:'국제지원팀',
        number:'200-6446~8'
    },
    {
        mode:2,
        name:'부민',
        organ:'국제교류처',
        office:'국제교류과',
        number:'200-6442~3'
    },
    //구덕
    {
        mode:3,
        name:'구덕',
        organ:'의과대학',
        office:'학장실',
        number:'240-2900'
    },
    {
        mode:3,
        name:'구덕',
        organ:'의학대학',
        office:'의학교육실',
        number:'240-2610'
    },
    {
        mode:3,
        name:'구덕',
        organ:'행정지원실(의과대학)',
        office:'행정지원실장실',
        number:'240-2910'
    },
    {
        mode:3,
        name:'구덕',
        organ:'행정지원실(의과대학)',
        office:'행정지원실',
        number:'240-2903~4'
    },
    {
        mode:3,
        name:'구덕',
        organ:'의예과',
        office:'의예과',
        number:'240-2944'
    },
];